library(remotes)
# install_version("mvtnorm", "1.0-10")
install_version("BayesFactor", "0.9.12-4.2", dependencies = TRUE, upgrade = TRUE)
install_version("statsr", "0.1-0", dependencies = TRUE, upgrade = TRUE)
# install_version("dplyr", "0.8.0.1")
# install_version("ggplot2", "3.1.0")
